//user
export const INIT_USER_DATA = 'INIT_USER_DATA';
//sound
export const CHANGE_SOUND_VALUE = 'CHANGE_SOUND_VALUE';
export const SET_AUDIO = 'SET_AUDIO';
export const AUDIO_PLAYING = 'AUDIO_PLAYING';
export const AUDIO_STOP = 'AUDIO_STOP';
export const CHANGE_RIGHTSIDE_TYPE = 'CHANGE_RIGHTSIDE_TYPE';
export const CHANGE_CHECK_ANSWER_STATE = 'CHANGE_CHECK_ANSWER_STATE';
export const CHANGE_SOUND_DURATION = 'CHANGE_SOUND_DURATION';
export const INIT_PAPER_DATA = 'INIT_PAPER_DATA';
export const CHANGE_PAPER_DATA = 'CHANGE_PAPER_DATA';
export const SET_AREA_INDEX = 'SET_AREA_INDEX';
export const SET_QUESTION_INDEX = 'SET_QUESTION_INDEX';
export const SET_CONTENT_INDEX = 'SET_CONTENT_INDEX';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const NEXT_AREA = 'NEXT_AREA';
export const RESET_QUESTION = 'RESET_QUESTION';
export const RESET_AREA = 'RESET_AREA';
export const CHANGE_PAPER_ANDWER = 'CHANGE_PAPER_ANDWER';
export const CHANGE_SOUND_SRC = 'CHANGE_SOUND_SRC';
export const CHANGE_TRAIN_RECORD_STATE = 'CHANGE_TRAIN_RECORD_STATE';
export const CHANGE_LOGINTYPE = 'CHANGE_LOGINTYPE';
export const CHANGE_IP = 'CHANGE_IP';
export const CHANGE_LISTEN_GUIDE = 'CHANGE_LISTEN_GUIDE';
export const CHANGE_LISTEN_QUESTION = 'CHANGE_LISTEN_QUESTION';
export const CHANGE_SECTION2 = 'CHANGE_SECTION2';
export const CHANGE_TRAINTYPE = 'CHANGE_TRAINTYPE';
export const BTN_LOADING = 'BTN_LOADING';
export const CHANGE_SELECTED_PAPER = 'CHANGE_SELECTED_PAPER';
export const RESET_PAPER_REDUCER = 'RESET_PAPER_REDUCER';
export const RESET_SOUND = 'RESET_SOUND';
export const CHANGE_SEATNO = 'CHANGE_SEATNO';


